apiVersion: apps/v1
kind: Deployment
metadata:
    name: deployment-cake
    labels:
      app: frontend
spec:
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: cakeshop-container
          image: dockerprabha2001/cakeshop-httpd
          ports:
           - containerPort: 80
  selector:
    matchLabels:
      app: frontend
  replicas: 4
