apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-deployment
    labels:
      app: frontend
spec:
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx
  selector:
    matchLabels:
      app: frontend
  replicas: 4
